@extends('layouts.app')
@section('title')
    Reçeteler
@endsection
@section('content')
        <table>
            <thead>
                <th>No</th>
                <th>Tür</th>
                <th>Tarih</th>
                <th>Klinik</th>
                <th>Doktor</th>
                <th>Hasta</th>
                <th>İlaclar</th>
            </thead>
            <tbody>

            </tbody>
        </table>
@endsection